import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
 title: "Vestigo Insurance Company",
  description: "Generated by ROHAN TEAM",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
      
        <Navbar /> 
        <div className="flex flex-col min-h-screen ">  
          <main className="flex-1 w-full">
            {children}
          </main>
        <Footer />

        </div>

      </body>
    </html>
  );
}
