import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/header";
import Footer from "./components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        
        {/* Fixed Navbar */}
        <Navbar />

        {/* Page Wrapper */}
        <div className="flex flex-col min-h-screen pt-16">
          
          {/* Main Content */}
          <main className="flex-1 w-full">
            {children}
          </main>

          {/* Footer */}
          <Footer />

        </div>

      </body>
    </html>
  );
}
